# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"  # A link title for your page.
  url = "publication/"  # The URL of your page.
  weight = 2  # The position of your page in the menu.

[[main]]
  name = "Projects"  # A link title for your page.
  url = "project/"  # The URL of your page.
  weight = 3  # The position of your page in the menu.

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 4

#[[main]]
#  name = "Blog"
#  url = "post/"
#  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "files/NCKeleher_CV.pdf"
  weight = 7
